In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [56]:
df = pd.read_csv("Churn_Modelling_Clean.csv",index_col=False)

In [57]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       1   42       2       0.00              1          1   
1          608       1   41       1   83807.86              1          0   
2          502       1   42       8  159660.80              3          1   
3          699       1   39       1       0.00              2          0   
4          850       1   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Germany  France  Spain  
0               1        101348.88       1        0       1      0  
1               1        112542.58       0        0       0      1  
2               0        113931.57       1        0       1      0  
3               0         93826.63       0        0       1      0  
4               1         79084.10       0        0       0      1

In [58]:
Y = np.array(df['Exited'])
X = df.drop(columns=['Exited'])
X_ar = np.array(X)
df.iloc[::]

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       1   42       2       0.00              1          1   
1             608       1   41       1   83807.86              1          0   
2             502       1   42       8  159660.80              3          1   
3             699       1   39       1       0.00              2          0   
4             850       1   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       0   39       5       0.00              2          1   
9996          516       0   35      10   57369.61              1          1   
9997          709       1   36       7       0.00              1          0   
9998          772       0   42       3   75075.31              2          1   
9999          792       1   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Germany  France  Spain  
0                  1        101348.88       1        0       1      0  
1                  1        112542.58       0        0       0      1  
2                  0        113931.57       1        0       1      0  
3                  0         93826.63       0        0       1      0  
4                  1         79084.10       0        0       0      1  
...              ...              ...     ...      ...     ...    ...  
9995               0         96270.64       0        0       1      0  
9996               1        101699.77       0        0       1      0  
9997               1         42085.58       1        0       1      0  
9998               0         92888.52       1        1       0      0  
9999               0         38190.78       0        0       1      0  

[10000 rows x 13 columns]

In [5]:
col_names = list(X.columns)
features = X[col_names]

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

ct = ColumnTransformer([
        ('somename', StandardScaler(), ['CreditScore', 'Balance','EstimatedSalary'])
    ], remainder='passthrough')

X = ct.fit_transform(features)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

## Logistic Regression

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)

cross_val_score(log_reg,X_train,y_train,cv=3, scoring="accuracy")

/Users/ihjas/miniforge3/envs/mda_3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ihjas/miniforge3/envs/mda_3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_

array([0.79946285, 0.8114644 , 0.81639051])

In [8]:
y_train_pred = cross_val_predict(log_reg,X_train,y_train,cv=3)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_train,y_train_pred)

/Users/ihjas/miniforge3/envs/mda_3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ihjas/miniforge3/envs/mda_3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_

array([[5117,  189],
       [1090,  304]])

In [9]:
from sklearn.metrics import precision_score,recall_score,f1_score

print('Precision:',precision_score(y_train,y_train_pred))
print('Recall:',recall_score(y_train,y_train_pred))
print('F1 Score:',f1_score(y_train,y_train_pred))

Precision: 0.6166328600405679
Recall: 0.21807747489239598
F1 Score: 0.32220455749867516


## KNN


In [10]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [11]:
cross_val_score(neigh,X_train,y_train,cv=3, scoring="accuracy")

array([0.79677708, 0.79355128, 0.80250784])

In [12]:
y_train_pred_neigh = cross_val_predict(neigh,X_train,y_train,cv=3)

confusion_matrix(y_train,y_train_pred_neigh)

array([[4849,  457],
       [ 899,  495]])

In [13]:
print('Precision:',precision_score(y_train,y_train_pred_neigh))
print('Recall:',recall_score(y_train,y_train_pred_neigh))
print('F1 Score:',f1_score(y_train,y_train_pred_neigh))

Precision: 0.5199579831932774
Recall: 0.3550932568149211
F1 Score: 0.421994884910486


## SVM

In [14]:
from sklearn.svm import LinearSVC

svm_clf = LinearSVC(C = 10, loss='hinge')
svm_clf.fit(X_train,y_train)

/Users/ihjas/miniforge3/envs/mda_3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC(C=10, loss='hinge')

In [15]:
cross_val_score(svm_clf,X_train,y_train,cv=3, scoring="accuracy")

/Users/ihjas/miniforge3/envs/mda_3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/ihjas/miniforge3/envs/mda_3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/ihjas/miniforge3/envs/mda_3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


array([0.41897941, 0.34527541, 0.79220779])

In [16]:
y_train_pred = cross_val_predict(svm_clf,X_train,y_train,cv=3)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_train,y_train_pred)

/Users/ihjas/miniforge3/envs/mda_3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/ihjas/miniforge3/envs/mda_3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/ihjas/miniforge3/envs/mda_3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


array([[3978, 1328],
       [ 909,  485]])

## Random Forest

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X_ar, Y, test_size=0.33, random_state=42)

In [61]:
X[1]

KeyError: 1

In [18]:
from sklearn.ensemble import RandomForestClassifier

rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, n_jobs=-1)
rnd_clf.fit(X_train,y_train)

RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, n_jobs=-1)

In [19]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

cross_val_score(rnd_clf,X_train,y_train,cv=3, scoring="accuracy")

array([0.84243509, 0.85356023, 0.84639498])

In [20]:
y_train_pred = cross_val_predict(rnd_clf,X_train,y_train,cv=3)

from sklearn.metrics import confusion_matrix

confusion_matrix(y_train,y_train_pred)

array([[5239,   67],
       [ 957,  437]])

In [21]:
from sklearn.metrics import precision_score,recall_score,f1_score

print('Precision:',precision_score(y_train,y_train_pred))
print('Recall:',recall_score(y_train,y_train_pred))
print('F1 Score:',f1_score(y_train,y_train_pred))

Precision: 0.8670634920634921
Recall: 0.3134863701578192
F1 Score: 0.4604847207586934


In [22]:
from sklearn.metrics import mean_squared_error
final_predictions = rnd_clf.predict(X_test)

final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
print("Mean Squared Error:", final_mse)
print("Root Mean Squared Error:", final_rmse)

Mean Squared Error: 0.14757575757575758
Root Mean Squared Error: 0.384155902695452


In [25]:
import joblib

joblib.dump(rnd_clf, "my_random_forest.joblib")

# loaded_rf = joblib.load("my_random_forest.joblib")

['my_random_forest.joblib']

In [26]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       1   42       2       0.00              1          1   
1          608       1   41       1   83807.86              1          0   
2          502       1   42       8  159660.80              3          1   
3          699       1   39       1       0.00              2          0   
4          850       1   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Germany  France  Spain  
0               1        101348.88       1        0       1      0  
1               1        112542.58       0        0       0      1  
2               0        113931.57       1        0       1      0  
3               0         93826.63       0        0       1      0  
4               1         79084.10       0        0       0      1

In [52]:
rnd_clf.predict([[502,1,42,8,159660,3,1,0,79084,0,0,1]])

array([1])

In [53]:
X_test[1]

array([6.230000e+02, 0.000000e+00, 4.300000e+01, 1.000000e+00,
       0.000000e+00, 2.000000e+00, 1.000000e+00, 1.000000e+00,
       1.463793e+05, 0.000000e+00, 1.000000e+00, 0.000000e+00])