In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("Churn_Modelling_Clean.csv",index_col=False)

In [3]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       1   42       2       0.00              1          1   
1          608       1   41       1   83807.86              1          0   
2          502       1   42       8  159660.80              3          1   
3          699       1   39       1       0.00              2          0   
4          850       1   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Germany  France  Spain  
0               1        101348.88       1        0       1      0  
1               1        112542.58       0        0       0      1  
2               0        113931.57       1        0       1      0  
3               0         93826.63       0        0       1      0  
4               1         79084.10       0        0       0      1

In [4]:
Y = np.array(df['Exited'])
X = df.drop(columns=['Exited'])
X_ar = np.array(X)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X_ar, Y, test_size=0.33, random_state=42)

In [6]:
from sklearn.ensemble import RandomForestClassifier

rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, n_jobs=-1)
rnd_clf.fit(X_train,y_train)

RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, n_jobs=-1)

In [7]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

cross_val_score(rnd_clf,X_train,y_train,cv=3, scoring="accuracy")

array([0.8442256, 0.8531124, 0.8450515])

In [8]:
y_train_pred = cross_val_predict(rnd_clf,X_train,y_train,cv=3)

from sklearn.metrics import confusion_matrix

confusion_matrix(y_train,y_train_pred)

array([[5241,   65],
       [ 953,  441]])

In [9]:
from sklearn.metrics import precision_score,recall_score,f1_score

print('Precision:',precision_score(y_train,y_train_pred))
print('Recall:',recall_score(y_train,y_train_pred))
print('F1 Score:',f1_score(y_train,y_train_pred))

Precision: 0.8715415019762845
Recall: 0.3163558106169297
F1 Score: 0.46421052631578946


In [10]:
from sklearn.metrics import mean_squared_error
final_predictions = rnd_clf.predict(X_test)

final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
print("Mean Squared Error:", final_mse)
print("Root Mean Squared Error:", final_rmse)

Mean Squared Error: 0.14454545454545453
Root Mean Squared Error: 0.38019133938775423


In [17]:
import joblib

joblib.dump(rnd_clf, "my_random_forest2.joblib")

# loaded_rf = joblib.load("my_random_forest.joblib")

['my_random_forest2.joblib']

In [12]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       1   42       2       0.00              1          1   
1          608       1   41       1   83807.86              1          0   
2          502       1   42       8  159660.80              3          1   
3          699       1   39       1       0.00              2          0   
4          850       1   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Germany  France  Spain  
0               1        101348.88       1        0       1      0  
1               1        112542.58       0        0       0      1  
2               0        113931.57       1        0       1      0  
3               0         93826.63       0        0       1      0  
4               1         79084.10       0        0       0      1

In [16]:
rnd_clf.predict([[699,1,39,1,0,2,0,0,93826,0,1,0]])

array([0])